Add terraform script for pubsub and update README.MD
weix0011/dataflow-sample-applications pull request #2
Opened 2021-01-28 01:06 UTC by weix0011

Started a new pull request for practice.

2021-01-28 13:24 UTC, tzehon commented on retail/retail-java-applications/README.MD
> +```
You can remove this portion

2021-01-28 13:25 UTC, tzehon commented on retail/retail-java-applications/README.MD
> +```
You can remove this part

2021-01-28 13:33 UTC, tzehon commented on retail/retail-java-applications/README.MD
> +
Add a section asking the user to look at the topic and subscription names in terraform.tfvars, explain that these are the defaults and that they can override them with their own names if desired

2021-01-28 13:33 UTC, tzehon commented on retail/retail-java-applications/variables.tf
> +}
Add a newline to satisfy the linter

2021-01-28 13:34 UTC, tzehon commented on retail/retail-java-applications/terraform.tfvars
> +inventory_inbound_sub      = "Inventory-inbound-sub"
Add a newline to satisfy the linter

2021-01-28 13:37 UTC, tzehon commented
Looking good, some minor comments.

2021-01-29 01:30 UTC, weix0011 commented on retail/retail-java-applications/README.MD
> +```
Removed accordingly.

2021-01-29 01:31 UTC, weix0011 commented on retail/retail-java-applications/README.MD
> +
Added a section about the resource names. Please take a look at it. Thank you.

2021-01-29 01:32 UTC, weix0011 commented on retail/retail-java-applications/variables.tf
> +}
Added a new line

2021-01-29 01:32 UTC, weix0011 commented on retail/retail-java-applications/terraform.tfvars
> +inventory_inbound_sub      = "Inventory-inbound-sub"
Added a new line

2021-02-01 11:45 UTC, tzehon commented on .gitignore
> +*.tfstate
The current .gitignore doesn't ignore terraform.tfstate.backup files, please modify it. Now that you're more familiar with .gitignore and Terraform in general, you can look at https://www.toptal.com/developers/gitignore which is a useful site to help generate .gitignore files. 

I wouldn't suggest always taking 100% of their generated .gitignore however, examine each line individually and take those that make sense in the context of each commit/project.

2021-02-01 11:45 UTC, tzehon requested changes
One comment on .gitignore, everything else looks good

2021-02-02 01:59 UTC, weix0011 commented on .gitignore
> +*.tfstate
Added *.tfstate.* to ignore terraform.tfstate.backup files. After looking at the generated .gitigore file, no additional file is included according to the following reasons.
1. crash.log - no crash log is expected as this project is straight forward
2. override.tf - there is no need to override existing tf files for now
3. tfplan files - tfplan files are generated according to users' need and could be named differently
Thank you for reviewing! :)

2021-02-03 04:13 UTC, tzehon approved these changes
LGTM

2021-02-03 04:15 UTC, tzehon commented
Click the big green 'Merge pull request' button, use the default option, and then leave it for now. I'll walk you through some extra setup you need to do for your GitHub account tomorrow so you can raise a PR for merging to upstream

2021-02-04 01:06 UTC, merged

2021-02-04 01:08 UTC, weix0011 commented
First merged PR! Thank you Tze Hon for your helpful reviews!